stages:
  - test
  - build_and_push

test:unit:
  stage: test
  script:
  - apt-get update && apt-get install -y make
  - make venv
  - make unittests

test:int:
  variables:
    POSTGRES_HOST: db
    POSTGRES_DB: kfailbot
    POSTGRES_USER: kfailb
    POSTGRES_PASSWORD: kfailb
  stage: test
  services:
  - name: postgres:11
    alias: db
  script:
  - apt-get update && apt-get install -y make
  - make venv
  - make integrationtests

build_and_push:
  image: docker:latest
  services:
    - docker:dind
  stage: build_and_push
  tags:
    - docker
  script:
    - export IMAGE_VERSION=${CI_COMMIT_TAG:-latest}
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_VERSION .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com      
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_VERSION
  only:
    - master
    - tags
